engines:
    eslint:
        enabled: true
    duplication:
        enabled: true
        config:
            languages:
                - javascript
    nodesecurity:
        enabled: true
ratings:
    paths:
        - models/**
        - test/**
        - '*.js'
